name: Sublime Syntax Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: SublimeText/syntax-test-action@v2
      with:
        build: 4016
        default_packages: st3
        package_name: Django Syntax

    - name: Run build.py check
      run: python3 build.py check
